CREATE TABLE "KAMERA" (
  id_kamera BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kamera TEXT NOT NULL CHECK (length(trim(nama_kamera)) > 0),
  merk TEXT NOT NULL CHECK (length(trim(merk)) > 0),
  jenis TEXT NOT NULL CHECK (length(trim(jenis)) > 0),
  harga_sewa_per_hari NUMERIC(12, 2) NOT NULL CHECK (harga_sewa_per_hari > 0),
  status TEXT NOT NULL DEFAULT 'Tersedia' CHECK (status IN ('Tersedia', 'Disewa'))
);

CREATE TABLE "PELANGGAN" (
  id_pelanggan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pelanggan TEXT NOT NULL CHECK (length(trim(nama_pelanggan)) > 0),
  no_telepon TEXT NOT NULL UNIQUE CHECK (length(trim(no_telepon)) > 0),
  alamat TEXT NOT NULL CHECK (length(trim(alamat)) > 0)
);

CREATE TABLE "TRANSAKSI_SEWA" (
  id_transaksi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_kamera BIGINT NOT NULL REFERENCES "KAMERA" (id_kamera) ON DELETE RESTRICT,
  id_pelanggan BIGINT NOT NULL REFERENCES "PELANGGAN" (id_pelanggan) ON DELETE RESTRICT,
  tanggal_sewa DATE NOT NULL,
  tanggal_kembali DATE NOT NULL,
  lama_sewa INTEGER NOT NULL CHECK (lama_sewa > 0),
  harga_per_hari NUMERIC(12, 2) NOT NULL CHECK (harga_per_hari > 0),
  total_pendapatan NUMERIC(14, 2) NOT NULL CHECK (total_pendapatan >= 0),
  status_sewa TEXT NOT NULL DEFAULT 'Aktif' CHECK (status_sewa IN ('Aktif', 'Selesai', 'Batal')),
  CONSTRAINT tanggal_kembali_setelah_sewa CHECK (tanggal_kembali > tanggal_sewa),
  CONSTRAINT lama_sewa_sesuai_tanggal CHECK (lama_sewa = tanggal_kembali - tanggal_sewa),
  CONSTRAINT total_sesuai_tarif CHECK (total_pendapatan = lama_sewa * harga_per_hari)
);

CREATE INDEX transaksi_sewa_kamera_idx ON "TRANSAKSI_SEWA" (id_kamera);
CREATE INDEX transaksi_sewa_pelanggan_idx ON "TRANSAKSI_SEWA" (id_pelanggan);
CREATE INDEX transaksi_sewa_status_idx ON "TRANSAKSI_SEWA" (status_sewa);

INSERT INTO "KAMERA" (nama_kamera, merk, jenis, harga_sewa_per_hari, status) VALUES
  ('Canon EOS R6', 'Canon', 'Mirrorless', 450000, 'Tersedia'),
  ('Sony A7 III', 'Sony', 'Mirrorless', 500000, 'Tersedia'),
  ('Canon 70D', 'Canon', 'DSLR', 300000, 'Disewa'),
  ('Fujifilm X-T4', 'Fujifilm', 'Mirrorless', 420000, 'Tersedia'),
  ('Nikon Z6 II', 'Nikon', 'Mirrorless', 475000, 'Tersedia');

INSERT INTO "PELANGGAN" (nama_pelanggan, no_telepon, alamat) VALUES
  ('Ayu Lestari', '081234567890', 'Jl. Merdeka No. 12, Bandung'),
  ('Budi Santoso', '082345678901', 'Jl. Cendana No. 45, Jakarta'),
  ('Citra Dewi', '083456789012', 'Jl. Melati No. 8, Surabaya'),
  ('Dimas Pratama', '081298765432', 'Jl. Pahlawan No. 7, Yogyakarta');

INSERT INTO "TRANSAKSI_SEWA" (
  id_kamera, id_pelanggan, tanggal_sewa, tanggal_kembali,
  lama_sewa, harga_per_hari, total_pendapatan, status_sewa
) VALUES
  (1, 1, CURRENT_DATE - 20, CURRENT_DATE - 18, 2, 450000, 900000, 'Selesai'),
  (2, 2, CURRENT_DATE - 14, CURRENT_DATE - 11, 3, 500000, 1500000, 'Selesai'),
  (3, 3, CURRENT_DATE - 1, CURRENT_DATE + 2, 3, 300000, 900000, 'Aktif');
;

CREATE TABLE "PEMBAYARAN" (
    id_pembayaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_transaksi BIGINT NOT NULL
        REFERENCES "TRANSAKSI_SEWA" (id_transaksi)
        ON DELETE RESTRICT,

    tanggal_pembayaran DATE NOT NULL DEFAULT CURRENT_DATE,

    jumlah_pembayaran NUMERIC(14, 2) NOT NULL
        CHECK (jumlah_pembayaran > 0),

    metode_pembayaran TEXT NOT NULL
        CHECK (
            metode_pembayaran IN (
                'Tunai',
                'Transfer Bank',
                'QRIS'
            )
        ),

    keterangan TEXT
);

CREATE INDEX pembayaran_transaksi_idx
ON "PEMBAYARAN" (id_transaksi);  ('Canon EOS R6', 'Canon', 'Mirrorless', 450000, 'Tersedia'),
  ('Sony A7 III', 'Sony', 'Mirrorless', 500000, 'Tersedia'),
  ('Canon 70D', 'Canon', 'DSLR', 300000, 'Disewa'),
  ('Fujifilm X-T4', 'Fujifilm', 'Mirrorless', 420000, 'Tersedia'),
  ('Nikon Z6 II', 'Nikon', 'Mirrorless', 475000, 'Tersedia');

INSERT INTO "PELANGGAN" (nama_pelanggan, no_telepon, alamat) VALUES
  ('Ayu Lestari', '081234567890', 'Jl. Merdeka No. 12, Bandung'),
  ('Budi Santoso', '082345678901', 'Jl. Cendana No. 45, Jakarta'),
  ('Citra Dewi', '083456789012', 'Jl. Melati No. 8, Surabaya'),
  ('Dimas Pratama', '081298765432', 'Jl. Pahlawan No. 7, Yogyakarta');

INSERT INTO "TRANSAKSI_SEWA" (
  id_kamera, id_pelanggan, tanggal_sewa, tanggal_kembali,
  lama_sewa, harga_per_hari, total_pendapatan, status_sewa
) VALUES
  (1, 1, CURRENT_DATE - 20, CURRENT_DATE - 18, 2, 450000, 900000, 'Selesai'),
  (2, 2, CURRENT_DATE - 14, CURRENT_DATE - 11, 3, 500000, 1500000, 'Selesai'),
  (3, 3, CURRENT_DATE - 1, CURRENT_DATE + 2, 3, 300000, 900000, 'Aktif');
